#!/bin/bash
args=" "
if [[ -n $1 ]]; then
	args=$1
fi

if [[ -n $2 ]]; then
	args="$args $2"
fi

if [[ -n $3 ]]; then
	args="$args $3"
fi

command="java -jar /d/Dev/Tool/xyz-decode.jar $args"
echo "execute 【 $command 】"
eval $command